'use client'

import { useState } from 'react'
import {
  ArrowRight,
  BookOpen,
  Check,
  ChevronDown,
  Code2,
  Grid2X2,
  Menu,
  Search,
  Sparkles,
  Users,
  X,
} from 'lucide-react'

const categories = ['Design', 'Development', 'IT & Software', 'Business', 'Marketing', 'Photography']
const filters = ['Featured', 'UI/UX', 'Drawing & Painting', 'Marketing', 'Animation', 'Social Media', 'User Experience', 'Content Marketing', 'Digital Illustration', 'Film & Video', 'Crafts', 'Healthcare & Entrepreneurship', 'Creative Design', 'Photography']
const courses = [
  { title: 'Learn Figma from Basic', category: 'Design', image: 'https://images.unsplash.com/photo-1558655146-d09347e92766?auto=format&fit=crop&w=700&q=80', price: '$25.00', rating: '4.5' },
  { title: 'Build Digital Asset', category: 'Development', image: 'https://images.unsplash.com/photo-1559028012-481c04fa702d?auto=format&fit=crop&w=700&q=80', price: '$26.00', rating: '4.8' },
  { title: 'The Power of Big Data', category: 'IT & Software', image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=700&q=80', price: '$25.00', rating: '4.5' },
  { title: 'Balancing Productivity on...', category: 'Business', image: 'https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=700&q=80', price: '$25.00', rating: '4.7' },
  { title: 'Mastering Money Manage...', category: 'Finance', image: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&w=700&q=80', price: '$25.00', rating: '4.6' },
  { title: 'From Idea to Startup Succ...', category: 'Business', image: 'https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=700&q=80', price: '$25.00', rating: '4.9' },
]

export function Brand({ light = false }: { light?: boolean }) {
  return <div className={`flex items-center gap-2 text-sm font-bold tracking-tight ${light ? 'text-white' : 'text-slate-900'}`}><span className="brand-mark">▸</span> ByteSpace</div>
}

export function Button({ children, variant = 'lime', className = '' }: { children: React.ReactNode; variant?: 'lime' | 'outline' | 'white'; className?: string }) {
  return <button className={`rounded-full px-5 py-2.5 text-xs font-semibold transition-transform hover:-translate-y-0.5 ${variant === 'lime' ? 'bg-lime-300 text-slate-950 hover:bg-lime-200' : variant === 'white' ? 'bg-white text-blue-700 hover:bg-slate-100' : 'border border-white/30 text-white hover:bg-white/10'} ${className}`}>{children}</button>
}

export function Navbar() {
  const [open, setOpen] = useState(false)
  return <header className="absolute inset-x-0 top-0 z-20"><div className="mx-auto flex max-w-6xl items-center justify-between px-5 py-5 lg:px-8"><Brand light /><nav className="hidden items-center gap-8 text-xs text-white/80 md:flex"><a href="#courses">Courses</a><a href="#paths">Categories</a><a href="#community">Community</a></nav><div className="hidden items-center gap-5 text-xs text-white md:flex"><a href="#login">Sign in</a><Button>Join us</Button></div><button aria-label="Toggle navigation" onClick={() => setOpen(!open)} className="text-white md:hidden">{open ? <X /> : <Menu />}</button></div>{open && <div className="mx-4 flex flex-col gap-4 rounded-2xl bg-blue-900 p-5 text-sm text-white md:hidden"><a href="#courses">Courses</a><a href="#paths">Categories</a><a href="#community">Community</a><a href="#login">Sign in</a><Button>Join us</Button></div>}</header>
}

export function Hero() {
  return <section className="hero-grid relative overflow-hidden bg-[#073ee5] px-5 pb-16 pt-32 text-white"><div className="blob blob-lime left-[-70px] top-24 h-16 w-32 rotate-25" /><div className="blob blob-lime right-[-45px] top-28 h-24 w-32 rotate-[-28deg]" /><div className="mx-auto max-w-4xl text-center"><p className="mb-4 text-[10px] font-semibold uppercase tracking-[0.25em] text-lime-300">Learn without limits</p><h1 className="mx-auto max-w-2xl text-4xl font-bold leading-[1.05] tracking-tight sm:text-6xl">Get Access to Hundreds of<br /> Courses Available</h1><p className="mx-auto mt-5 max-w-lg text-xs leading-6 text-blue-100">Unlock your potential with industry-leading courses designed to help you master new skills and reach your goals.</p><div className="mx-auto mt-6 flex max-w-sm items-center rounded-full bg-white p-1"><Search className="ml-3 size-4 text-slate-400" /><input aria-label="Search courses" className="min-w-0 flex-1 bg-transparent px-2 text-xs text-slate-800 outline-none" placeholder="Search for a course" /><Button className="px-4 py-2">Search</Button></div></div><div className="mx-auto mt-14 flex max-w-3xl items-end justify-center gap-4"><div className="hidden rounded-xl bg-white p-3 text-left text-[9px] text-slate-800 shadow-xl sm:block"><b>Happy Students</b><div className="mt-2 text-lime-600">★★★★★</div></div><div className="relative h-48 w-52 rounded-t-[45%] bg-gradient-to-br from-lime-300 to-lime-500 sm:h-60 sm:w-64"><div className="absolute inset-x-5 bottom-0 top-10 rounded-t-[45%] bg-gradient-to-b from-amber-100 to-amber-700 opacity-80" /><div className="absolute bottom-[-8px] left-1/2 h-32 w-24 -translate-x-1/2 rounded-full bg-slate-700/80" /><div className="absolute right-[-28px] top-10 hidden w-28 rounded-lg bg-white p-3 text-left text-slate-900 shadow-xl sm:block"><span className="text-[9px]">Learning Progress</span><strong className="block text-2xl">55%</strong><div className="mt-1 h-1 rounded-full bg-lime-300" /></div></div><div className="hidden rounded-xl bg-white p-3 text-left text-[9px] text-slate-800 shadow-xl sm:block"><b>New skills</b><div className="mt-2 flex -space-x-1"><span className="size-4 rounded-full bg-rose-300" /><span className="size-4 rounded-full bg-blue-300" /><span className="size-4 rounded-full bg-amber-300" /></div></div></div></section>
}

export function LogoStrip() { return <div className="flex flex-wrap justify-center gap-x-10 gap-y-4 bg-slate-50 px-5 py-7 text-[10px] font-semibold text-slate-500"><span>◉ Logopsum</span><span>✺ Logopsum</span><span>◈ Logopsum</span><span>✹ Logopsum</span><span>◌ Logopsum</span></div> }

export function CourseCard({ course }: { course: typeof courses[number] }) { return <article className="overflow-hidden rounded-2xl border border-slate-200 bg-white p-1.5"><img src={course.image} alt={course.title} className="h-28 w-full rounded-xl object-cover" /><div className="p-2"><h3 className="truncate text-[11px] font-bold text-slate-900">{course.title}</h3><div className="mt-1 flex justify-between text-[9px] text-slate-400"><span>{course.category}</span><span>★ {course.rating}</span></div><div className="mt-3 flex items-center justify-between"><span className="text-xs font-bold text-blue-600">{course.price}</span><span className="flex -space-x-1"><i className="size-4 rounded-full bg-amber-200" /><i className="size-4 rounded-full bg-blue-200" /><i className="size-4 rounded-full bg-lime-300" /></span></div></div></article> }

export function Courses() { return <section id="courses" className="mx-auto max-w-6xl px-5 py-16"><div className="mx-auto max-w-xl text-center"><h2 className="text-2xl font-bold text-slate-900">Discover Your Passion,<br /> Build Your Skills</h2><p className="mt-3 text-xs leading-5 text-slate-500">Find courses that fit your interests and goals. Learn from experts and grow with a community that keeps you moving forward.</p></div><div className="mx-auto mt-7 flex max-w-4xl flex-wrap justify-center gap-2">{filters.map((filter, index) => <button key={filter} className={`rounded-full px-3 py-1.5 text-[9px] ${index === 0 ? 'bg-lime-300 text-slate-900' : 'bg-slate-100 text-slate-500'}`}>{filter}</button>)}</div><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{courses.map((course) => <CourseCard key={course.title} course={course} />)}</div></section> }

export function Paths() { return <section id="paths" className="bg-slate-50 px-5 py-14"><div className="mx-auto max-w-6xl text-center"><h2 className="text-xl font-bold text-slate-900">Explore Diverse Learning Paths at ByteSpace</h2><p className="mx-auto mt-3 max-w-xl text-xs leading-5 text-slate-500">Whether you are just beginning or advancing your career, discover the right path for your goals.</p><div className="mt-8 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-6">{categories.map((item, index) => <div key={item} className="rounded-xl border border-slate-200 bg-white p-5 text-xs font-semibold text-slate-700"><div className="mx-auto mb-3 flex size-8 items-center justify-center rounded-full bg-lime-300 text-slate-900">{[<Sparkles key="a" />, <Code2 key="b" />, <Grid2X2 key="c" />, <BookOpen key="d" />, <Users key="e" />, <Sparkles key="f" />][index]}</div>{item}</div>)}</div></div></section> }

export function Growth() { return <section className="relative overflow-hidden bg-gradient-to-br from-lime-100 via-white to-blue-100 px-5 py-16"><div className="mx-auto grid max-w-5xl items-center gap-12 lg:grid-cols-2"><div><p className="mb-3 text-xs font-bold uppercase tracking-wider text-blue-600">Your journey starts here</p><h2 className="max-w-md text-3xl font-bold leading-tight text-slate-900">Your Path to Professional Growth Starts Here!</h2><p className="mt-5 max-w-md text-xs leading-6 text-slate-600">Explore courses designed to help you become your best self. Learn at your own pace, build skills, and connect with a supportive community.</p><div className="mt-7 flex gap-8"><span><b className="block text-xl text-blue-700">12K</b><small className="text-[10px] text-slate-500">Students</small></span><span><b className="block text-xl text-blue-700">70+</b><small className="text-[10px] text-slate-500">Courses</small></span><span><b className="block text-xl text-blue-700">16</b><small className="text-[10px] text-slate-500">Creators</small></span></div></div><div className="relative mx-auto h-72 w-72"><div className="absolute inset-5 rounded-full bg-lime-300/80 blur-2xl" /><div className="absolute bottom-0 left-10 h-56 w-44 rounded-[45%] bg-gradient-to-br from-blue-700 to-slate-800" /><div className="absolute left-1/2 top-3 h-36 w-28 -translate-x-1/2 rounded-[45%] bg-gradient-to-b from-amber-100 to-amber-700" /><div className="absolute right-0 top-16 rounded-xl bg-white p-3 text-slate-900 shadow-lg"><span className="text-[9px]">Learning Progress</span><strong className="block text-2xl">55%</strong></div></div></div></section> }

export function Community() { const testimonials = [{name: 'Sarah M.', role: 'Entrepreneur & Learner'}, {name: 'James L.', role: 'Product Designer'}, {name: 'Alex B.', role: 'Tech Enthusiast'}]; return <section id="community" className="px-5 py-16"><div className="mx-auto grid max-w-6xl gap-8 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><div><h2 className="text-2xl font-bold text-slate-900">Discover What Our<br /> Community Is Saying</h2><p className="mt-4 max-w-sm text-xs leading-6 text-slate-500">Real stories from people who are learning, building, and growing with ByteSpace.</p></div><div className="grid gap-4 sm:grid-cols-3">{testimonials.map((person, index) => <article key={person.name} className="rounded-2xl bg-slate-50 p-5"><div className={`mb-4 size-9 rounded-full ${index === 0 ? 'bg-amber-300' : index === 1 ? 'bg-slate-400' : 'bg-blue-300'}`} /><h3 className="text-xs font-bold text-slate-900">{person.name}</h3><p className="mt-1 text-[9px] font-semibold text-blue-600">{person.role}</p><p className="mt-4 text-[10px] leading-5 text-slate-600">“ByteSpace made learning feel simple and inspiring. I have grown so much since joining this community.”</p></article>)}</div></div></section> }

export function CTA() { return <section className="hero-grid bg-[#073ee5] px-5 py-16 text-center text-white"><h2 className="text-3xl font-bold">Unlock Your Potential as a<br /> Creator with ByteSpace</h2><p className="mx-auto mt-4 max-w-lg text-xs leading-6 text-blue-100">Learn from the best, connect with a community of creators, and build the future you imagine.</p><Button className="mt-7">Join ByteSpace <ArrowRight className="ml-2 inline size-3" /></Button></section> }

export function Footer() { return <footer className="border-t border-slate-200 bg-white px-5 py-12"><div className="mx-auto grid max-w-6xl gap-10 md:grid-cols-[1.5fr_1fr_1fr_1fr]"><div><Brand /><p className="mt-4 max-w-xs text-[10px] leading-5 text-slate-500">Your space to learn, create, and grow with people who believe in the power of curiosity.</p><div className="mt-5 flex max-w-xs rounded-full border border-slate-200 p-1"><input className="min-w-0 flex-1 px-3 text-[10px] outline-none" placeholder="Enter your email" /><Button className="px-4 py-2">Submit</Button></div></div>{[['Explore', 'Courses', 'Categories', 'Community'], ['Resources', 'Blog', 'Help center', 'Events'], ['Company', 'About us', 'Careers', 'Contact']].map(([heading, ...links]) => <div key={heading}><h3 className="text-xs font-bold text-slate-900">{heading}</h3><div className="mt-4 flex flex-col gap-3 text-[10px] text-slate-500">{links.map(link => <a href="#" key={link}>{link}</a>)}</div></div>)}</div><div className="mx-auto mt-10 max-w-6xl border-t border-slate-100 pt-5 text-[9px] text-slate-400">© 2024 ByteSpace. All rights reserved.</div></footer> }